DROP TABLE IF EXISTS    `myloanworld`.`applicationDetail`;
DROP TABLE IF EXISTS   `myloanworld`.`applicationStatus`;
DROP TABLE IF EXISTS   `myloanworld`.`applicationType`;
DROP TABLE IF EXISTS   `myloanworld`.`customerRoleType`;
DROP TABLE IF EXISTS   `myloanworld`.`myLoanWorldUser`;
DROP TABLE IF EXISTS   `myloanworld`.`enquiry`;
DROP TABLE IF EXISTS   `myloanworld`.`customer`;
DROP TABLE IF EXISTS   `myloanworld`.`roleType`;
DROP TABLE IF EXISTS   `myloanworld`.`menus`;
DROP TABLE IF EXISTS   `myloanworld`.`applicationHistory`;
DROP TABLE IF EXISTS   `myloanworld`.`maritalStatus`;
DROP TABLE IF EXISTS   `myloanworld`.`contactDetails`;

DROP procedure IF EXISTS `myloanworld`.`save_Application`;
DROP procedure IF EXISTS `myloanworld`.`change_Application_Status`;
DROP procedure IF EXISTS `myloanworld`.`get_ApplicationById`;
DROP procedure IF EXISTS `myloanworld`.`get_Customer`;
DROP procedure IF EXISTS `myloanworld`.`save_Enquiry`;
DROP procedure IF EXISTS `myloanworld`.`update_Customer`;
DROP procedure IF EXISTS `myloanworld`.`forgot_Password`;
DROP procedure IF EXISTS `myloanworld`.`create_Password`;
DROP procedure IF EXISTS `myloanworld`.`authenticate_User`;
DROP procedure IF EXISTS `myloanworld`.`update_applicationStatus`;
DROP procedure IF EXISTS `myloanworld`.`save_applicationStatus`;
DROP procedure IF EXISTS `myloanworld`.`update_applicationType`;
DROP procedure IF EXISTS `myloanworld`.`save_applicationType`;
DROP procedure IF EXISTS `myloanworld`.`get_ApplicationList`;
DROP procedure IF EXISTS `myloanworld`.`update_contactDetails`;
DROP procedure IF EXISTS `myloanworld`.`get_menusByRole`
