DROP TABLE `myloanworld`.`applicationDetail`;
DROP TABLE `myloanworld`.`applicationStatus`;
DROP TABLE `myloanworld`.`applicationType`;
DROP TABLE `myloanworld`.`customerRoleType`;
DROP TABLE `myloanworld`.`myLoanWorldUser`;
DROP TABLE `myloanworld`.`enquiry`;
DROP TABLE `myloanworld`.`customer`;
DROP TABLE `myloanworld`.`roleType`;
DROP TABLE `myloanworld`.`menus`;
DROP TABLE `myloanworld`.`applicationHistory`;
DROP TABLE `myloanworld`.`maritalStatus`;

DROP procedure  IF EXISTS   `save_Application`;
DROP procedure IF EXISTS `change_Application_Status`;
DROP procedure IF EXISTS `get_ApplicationById`;
DROP procedure IF EXISTS `get_Customer`;
DROP procedure IF EXISTS `save_Enquiry`;
DROP procedure IF EXISTS `update_Customer`;
DROP procedure IF EXISTS `forgot_Password`;
DROP procedure IF EXISTS `create_Password`;
DROP procedure IF EXISTS `authenticate_User`;
DROP procedure IF EXISTS `update_applicationStatus`;
DROP procedure IF EXISTS `save_applicationStatus`;
DROP procedure IF EXISTS `update_applicationType`;
DROP procedure IF EXISTS `save_applicationType`;
